// Round-2 word-list expansion candidates.
// Dedupes against the live pool (normalized franco AND Arabic), assigns
// selection codes, prints the grouped list, and writes the code->entry map to
// the scratchpad for the later "save these" step.
// Run: node scripts/proposeWords.js
const fs = require('fs');
const { normalize } = require('../server/matching');
const { fullPool } = require('../server/engine');

// [fr, ar, flag?]  — flag '⚠️' = spelling/fame I'm less sure of
const CANDIDATES = {
  Media: [
    ['X-Large', 'إكس لارج'],
    ['3emaret Yacoubian', 'عمارة يعقوبيان'],
    ['Mafia', 'مافيا'],
    ['Sahar el Layaly', 'سهر الليالي'],
    ['Abo Ali', 'أبو علي'],
    ['Harameya fe KG2', 'حرامية في كي جي تو'],
    ['55 Es3af', '٥٥ إسعاف'],
    ['Sa3a w Nos', 'ساعة ونص'],
    ['Ghabi Meno Feeh', 'غبي منه فيه'],
    ['Foul el Seen el 3azeem', 'فول الصين العظيم'],
    ['Morgan Ahmed Morgan', 'مرجان أحمد مرجان'],
    ['Khalty Faransa', 'خالتي فرنسا'],
    ['Elly Baly Balak', 'اللي بالي بالك'],
    ['Esma3leya Rayeh Gay', 'إسماعيلية رايح جاي'],
    ['3askar fel Mo3askar', 'عسكر في المعسكر'],
    ['Meedo Mashakel', 'ميدو مشاكل'],
    ['La Tarago3 wala Estislam', 'لا تراجع ولا استسلام'],
    ['H Dabbour', 'اتش دبور'],
    ['Samir w Shahir w Bahir', 'سمير وشهير وبهير'],
    ['El Mamar', 'الممر'],
    ['Casablanca', 'كازابلانكا'],
    ['El 3aref', 'العارف'],
    ['Hepta', 'هيبتا'],
    ['El Serb', 'السرب'],
    ['Layaly el Helmeya', 'ليالي الحلمية'],
    ['Ra2fat el Hagan', 'رأفت الهجان'],
    ['Zizinya', 'زيزينيا'],
    ['B100 Wesh', 'بـ100 وش'],
    ['Weld el Ghalaba', 'ولد الغلابة'],
    ['Gafar el Omda', 'جعفر العمدة'],
    ['Lam Shamseya', 'لام شمسية'],
  ],
  Songs: [
    ['El Bakht', 'البخت'],
    ['El Sekka Shemal', 'السكة شمال'],
    ['James Dean', 'جيمس دين'],
    ['Kan Lak Ma3aya', 'كان لك معايا'],
    ['Sawt el Horreya', 'صوت الحرية'],
    ['Zahma Ya Donya Zahma', 'زحمة يا دنيا زحمة'],
    ['Ah Law Le3ebt Ya Zahr', 'اه لو لعبت يا زهر'],
    ['Number One', 'نمبر وان'],
    ['El Melouk', 'الملوك'],
    ['Sabry Aleel', 'صبري قليل'],
    ['Ma Sherbtesh men Nelha', 'ماشربتش من نيلها'],
    ['Leih Beydary Keda', 'ليه بيداري كده'],
    ['Boshret Kheir', 'بشرة خير'],
    ['Shik Shak Shok', 'شيك شاك شوك'],
    ['Ah W Noss', 'آه ونص'],
    ['Akhasmak Ah', 'أخاصمك آه'],
    ['Salmonella', 'سالمونيلا'],
    ['Ghaba', 'غابة', '⚠️'],
    ['Barbary', 'بربري', '⚠️'],
  ],
  People: [
    ['Donia Samir Ghanem', 'دنيا سمير غانم'],
    ['Emy Samir Ghanem', 'إيمي سمير غانم'],
    ['Hamdy el Mirghany', 'حمدي الميرغني'],
    ['Oka w Ortega', 'أوكا وأورتيجا'],
    ['Mostafa Khater', 'مصطفى خاطر'],
    ['Ahmed Amin', 'أحمد أمين'],
    ['Amina Khalil', 'أمينة خليل'],
    ['Jamila Awad', 'جميلة عوض'],
    ['Karim Mahmoud Abdelaziz', 'كريم محمود عبد العزيز'],
    ['Ghada Adel', 'غادة عادل'],
    ['Sherif Mounir', 'شريف منير'],
    ['Khaled el Nabawy', 'خالد النبوي'],
    ['Mahmoud Abdel Aziz', 'محمود عبد العزيز'],
    ['Fouad el Mohandes', 'فؤاد المهندس'],
    ['Abla Kamel', 'عبلة كامل'],
    ['Karima Mokhtar', 'كريمة مختار'],
    ['Nadia el Gendy', 'نادية الجندي'],
    ['Nabila Ebeid', 'نبيلة عبيد'],
    ['Elham Shahin', 'إلهام شاهين'],
    ['Fifi Abdou', 'فيفي عبده'],
    ['Shadia', 'شادية'],
    ['Rushdy Abaza', 'رشدي أباظة'],
    ['Sohair el Bably', 'سهير البابلي'],
    ['Salah el Saadany', 'صلاح السعدني'],
    ['Lotfy Labib', 'لطفي لبيب'],
    ['Naguib Mahfouz', 'نجيب محفوظ'],
    ['Taha Hussein', 'طه حسين'],
    ['Ahmed Zewail', 'أحمد زويل'],
    ['Magdy Yacoub', 'مجدي يعقوب'],
    ['El Sheikh el Sha3rawy', 'الشيخ الشعراوي'],
    ['El Malek Farouk', 'الملك فاروق'],
    ['Cleopatra', 'كليوباترا'],
    ['Tut Ankh Amon', 'توت عنخ آمون'],
    ['Nefertiti', 'نفرتيتي'],
    ['Mortada Mansour', 'مرتضى منصور', '⚠️'],
    ['Hakim', 'حكيم'],
    ['Mostafa Amar', 'مصطفى قمر'],
    ['Hisham Abbas', 'هشام عباس'],
    ['Bahaa Sultan', 'بهاء سلطان', '⚠️'],
    ['Asala', 'أصالة'],
    ['Ramy Sabry', 'رامي صبري', '⚠️'],
    ['Essam Sasa', 'عصام صاصا', '⚠️'],
  ],
  Football: [
    ['Pyramids', 'بيراميدز'],
    ['Kahraba', 'كهربا'],
    ['Afsha', 'أفشة'],
    ['Abdallah el Said', 'عبد الله السعيد'],
    ['Tarek Hamed', 'طارق حامد'],
    ['Wessam Abou Ali', 'وسام أبو علي'],
    ['Saleh Selim', 'صالح سليم'],
    ['Mosimane', 'موسيماني', '⚠️'],
    ['Essam el Shawaly', 'عصام الشوالي', '⚠️'],
    ['Messi', 'ميسي', '⚠️'],
    ['Ronaldo', 'رونالدو', '⚠️'],
  ],
  Places: [
    ['Madinet Nasr', 'مدينة نصر'],
    ['Shobra', 'شبرا'],
    ['Ain Shams', 'عين شمس'],
    ['Helwan', 'حلوان'],
    ['El Matareya', 'المطرية'],
    ['El Sayeda Zeinab', 'السيدة زينب'],
    ['El Hussein', 'الحسين'],
    ['Garden City', 'جاردن سيتي'],
    ['El Korba', 'الكوربة'],
    ['Roxy', 'روكسي'],
    ['Rod el Farag', 'روض الفرج'],
    ['El Mansoura', 'المنصورة'],
    ['El Ismailia', 'الإسماعيلية'],
    ['El Suez', 'السويس'],
    ['Dumyat', 'دمياط'],
    ['Kafr el Sheikh', 'كفر الشيخ'],
    ['Beni Suef', 'بني سويف'],
    ['El Zagazig', 'الزقازيق'],
    ['El Mahalla', 'المحلة'],
    ['Damanhour', 'دمنهور'],
    ['Siwa', 'سيوة'],
    ['Ras Sedr', 'رأس سدر'],
    ['Saint Catherine', 'سانت كاترين'],
    ['Marsa Alam', 'مرسى علم'],
    ['Sahl Hasheesh', 'سهل حشيش'],
    ['Somabay', 'سوما باي'],
    ['El Montaza', 'المنتزه'],
    ['Stanley', 'ستانلي'],
    ['El 3asema el Edareya', 'العاصمة الإدارية'],
    ['El Mat7af el Kebeer', 'المتحف الكبير'],
    ['El Mat7af el Masry', 'المتحف المصري'],
    ['Asr el Baron', 'قصر البارون'],
    ['Asr Abdeen', 'قصر عابدين'],
    ['Gam3et el Qahira', 'جامعة القاهرة'],
    ['Matar el Qahira', 'مطار القاهرة'],
    ['El Qanater', 'القناطر الخيرية'],
    ['El Sad el 3aly', 'السد العالي'],
    ['El Karnak', 'الكرنك'],
    ['Wadi el Melouk', 'وادي الملوك'],
    ['Ma3bad Hatshepsut', 'معبد حتشبسوت'],
    ['El Me7war', 'المحور'],
    ['3abbas el 3akkad', 'عباس العقاد'],
    ['Hadeeqet el Azhar', 'حديقة الأزهر'],
    ['El Metro', 'المترو'],
  ],
  Food: [
    ['Mombar', 'ممبار'],
    ['Kaware3', 'كوارع'],
    ['Torshy', 'طرشي'],
    ['Besara', 'بصارة'],
    ['Kishk', 'كشك', '⚠️'],
    ['Makarona bel Bashamel', 'مكرونة بالبشاميل'],
    ['Shorbet 3ads', 'شوربة عدس'],
    ['Tahina', 'طحينة'],
    ['Lo2met el Ady', 'لقمة القاضي'],
    ['Ghazl el Banat', 'غزل البنات'],
    ['Halawet el Mouled', 'حلاوة المولد'],
    ['Homos el Sham', 'حمص الشام'],
    ['Fool Sudani', 'فول سوداني'],
    ['Leb', 'لب'],
    ['Termes', 'ترمس'],
    ['Freska', 'فريسكا'],
    ['3eish el Saraya', 'عيش السرايا'],
    ['Roz Me3ammar', 'رز معمر'],
    ['Sayadeya', 'صيادية'],
    ['Gambary', 'جمبري'],
    ['Basterma', 'بسطرمة'],
    ['Lanshon', 'لانشون'],
    ['Baklawa', 'بقلاوة'],
    ['Kharoub', 'خروب'],
    ['Asab', 'قصب'],
    ['Indomie', 'اندومي'],
    ['Sobhy Kaber', 'صبحي كابر'],
    ['El Dahan', 'الدهان'],
    ['Abou Shakra', 'أبو شقرة'],
    ['Bazooka', 'بازوكا'],
    ['Zooba', 'زوبا'],
    ['El Shabrawy', 'الشبراوي'],
    ['Fool Mohamed Ahmed', 'فول محمد أحمد'],
    ['El Refa3y', 'الرفاعي', '⚠️'],
    ['Andrea', 'أندريا', '⚠️'],
    ['Balbaa', 'بلبع', '⚠️'],
  ],
  Characters: [
    ['Sayed Abo Hafiza', 'سيد أبو حفيظة'],
    ['Timon w Pumba', 'تيمون وبومبا'],
    ['Simba', 'سيمبا'],
    ['Buzz Yateer', 'باز يطير'],
    ['Woody', 'وودي'],
    ['Nemo', 'نيمو'],
    ['Tarzan', 'طرزان'],
    ['Mowgli', 'ماوكلي'],
    ['Cinderella', 'سندريلا'],
    ['Bayad el Talg', 'بياض الثلج', '⚠️'],
    ['Elsa', 'إلسا', '⚠️'],
    ['Minions', 'المينيونز'],
    ['Captain Majid', 'الكابتن ماجد'],
    ['Naruto', 'ناروتو'],
    ['Superman', 'سوبرمان'],
    ['Spider-Man', 'سبايدر مان'],
    ['Hulk', 'هالك', '⚠️'],
    ['Mario', 'ماريو'],
    ['Crash', 'كراش'],
    ['3am Dahab', 'عم دهب', '⚠️'],
  ],
  Platforms: [
    ['WhatsApp', 'واتساب'],
    ['Instagram', 'انستجرام'],
    ['YouTube', 'يوتيوب'],
    ['Twitter', 'تويتر'],
    ['Telegram', 'تليجرام'],
    ['Snapchat', 'سناب شات'],
    ['Google', 'جوجل'],
    ['ChatGPT', 'شات جي بي تي'],
    ['Spotify', 'سبوتيفاي'],
    ['PlayStation', 'بلايستيشن'],
    ['PUBG', 'ببجي'],
    ['Free Fire', 'فري فاير', '⚠️'],
    ['PES', 'بيس', '⚠️'],
    ['Pepsi', 'بيبسي'],
    ['Coca Cola', 'كوكاكولا'],
    ['Schweppes', 'شويبس'],
    ['Spiro Spathis', 'سبيرو سباتس'],
    ['Rani', 'راني'],
    ['Faragello', 'فراجيلو'],
    ['Corona', 'كورونا'],
    ['Covertina', 'كوفرتينا'],
    ['Hohos', 'هوهوز'],
    ['Todo', 'تودو'],
    ['Bake Rolz', 'بيك رولز'],
    ['Panda', 'بندة'],
    ['Almarai', 'المراعي'],
    ['Beyti', 'بيتي'],
    ['Zanussi', 'زانوسي'],
    ['Omar Effendi', 'عمر أفندي'],
    ['El Tawheed wel Nour', 'التوحيد والنور'],
    ['Hyper One', 'هايبر وان'],
    ['Awlad Ragab', 'أولاد رجب'],
    ['Kheir Zaman', 'خير زمان', '⚠️'],
    ['Abu Auf', 'أبو عوف'],
    ['La Poire', 'لابوار', '⚠️'],
    ['Shein', 'شي إن', '⚠️'],
    ['Town Team', 'تاون تيم', '⚠️'],
    ['Lada', 'لادا', '⚠️'],
  ],
  'TV Programs': [
    ['Masrah Masr', 'مسرح مصر'],
    ['Hany Haz el Gabal', 'هاني هز الجبل'],
    ['Man Sayarbah el Malyon', 'من سيربح المليون'],
    ['Fawazeer Ramadan', 'فوازير رمضان'],
  ],
  'Egyptian Life': [
    ['Tuk Tuk', 'توك توك'],
    ['Microbus', 'ميكروباص'],
    ['El Bawab', 'البواب'],
    ['El Makwagy', 'المكوجي'],
    ['El Mesaharaty', 'المسحراتي'],
    ['Fanoos Ramadan', 'فانوس رمضان'],
    ['Madfa3 el Iftar', 'مدفع الإفطار'],
    ['El 3edeya', 'العيدية'],
    ['El Zaffa', 'الزفة'],
    ['El Seboo3', 'السبوع'],
    ['El 3ozouma', 'العزومة'],
    ['Katb el Ketab', 'كتب الكتاب'],
    ['El Shabka', 'الشبكة'],
    ['El 7enna', 'الحنة'],
    ['Galabeya', 'جلابية'],
    ['Tarboosh', 'طربوش'],
    ['Shibshib', 'شبشب'],
    ['3arouset el Mouled', 'عروسة المولد'],
    ['El Aragoz', 'الأراجوز'],
    ['Sandou2 el Donia', 'صندوق الدنيا'],
    ['Tabla', 'طبلة'],
    ['Sheesha', 'الشيشة'],
    ['Tawla', 'الطاولة'],
    ['Domino', 'الدومينو'],
    ['Estoghomaya', 'الاستغماية'],
    ['Belya', 'البلي', '⚠️'],
    ['El 7agla', 'الحجلة', '⚠️'],
    ['Gawaz Salonat', 'جواز صالونات'],
  ],
};

// Code prefixes per category (matches earlier rounds where possible).
const PREFIX = {
  Media: 'M', Songs: 'S', People: 'H', Football: 'B', Places: 'P',
  Food: 'F', Characters: 'C', Platforms: 'A', 'TV Programs': 'T', 'Egyptian Life': 'E',
};

// Everything already in the live pool, normalized.
const saved = new Set();
for (const p of fullPool()) for (const f of p.forms) saved.add(f);

const map = {};
let md = '';
let kept = 0, dropped = [];

for (const [cat, items] of Object.entries(CANDIDATES)) {
  const prefix = PREFIX[cat];
  const seen = new Set();
  const rows = [];
  let idx = 0;
  for (const [fr, ar, flag] of items) {
    const frN = normalize(fr), arN = normalize(ar);
    if (saved.has(frN) || (arN && saved.has(arN))) { dropped.push(`${fr} (already in pool)`); continue; }
    if (seen.has(frN) || (arN && seen.has(arN))) { dropped.push(`${fr} (dup in proposal)`); continue; }
    seen.add(frN); if (arN) seen.add(arN);
    idx++;
    const code = prefix + idx;
    map[code] = { category: cat, fr, ar };
    rows.push(`\`${code}\` ${fr} · ${ar}${flag ? ' ' + flag : ''}`);
    kept++;
  }
  md += `\n**${cat}** (${rows.length})\n\n` + rows.join(' ｜ ') + '\n';
}

fs.writeFileSync(
  'C:/Users/Ali/AppData/Local/Temp/claude/E--/e1c39c24-7759-49df-aa65-5a4189758a4b/scratchpad/suggestions2.json',
  JSON.stringify(map, null, 1), 'utf8'
);

console.log(md);
console.log(`\n---\n${kept} candidates (${dropped.length} dropped: ${dropped.join(', ') || 'none'})`);
console.log('Code map saved to scratchpad/suggestions2.json');
