// Merges the round-2 approved suggestions (ALL of scratchpad/suggestions2.json)
// into server/data/wordLists.js. Dedupes against the existing pool AND within
// the additions (by normalized franco OR Arabic). "Egyptian Life" is appended
// as a new category. Run: node scripts/saveSelected2.js
const fs = require('fs');
const path = require('path');
const { normalize } = require('../server/matching');
const existing = require('../server/data/wordLists').lists;

const MAP = JSON.parse(fs.readFileSync(
  'C:/Users/Ali/AppData/Local/Temp/claude/E--/e1c39c24-7759-49df-aa65-5a4189758a4b/scratchpad/suggestions2.json', 'utf8'));

// Order codes per category by their numeric index.
const codeNum = (c) => parseInt(c.replace(/^[A-Z]+/, ''), 10);
const codes = Object.keys(MAP).sort((a, b) => {
  const ca = MAP[a].category, cb = MAP[b].category;
  if (ca !== cb) return ca < cb ? -1 : 1;
  return codeNum(a) - codeNum(b);
});

// Seed dedupe set with everything already saved.
const seen = new Set();
for (const list of existing) {
  for (const e of list.entries) {
    for (const f of [e.fr, e.ar, ...(e.accept || [])]) { const n = normalize(f); if (n) seen.add(n); }
  }
}

const additions = {}; // category -> [{fr, ar}]
const collapsed = [];
for (const code of codes) {
  const e = MAP[code];
  const frN = normalize(e.fr), arN = normalize(e.ar);
  if (!frN) continue;
  if (seen.has(frN) || (arN && seen.has(arN))) { collapsed.push(`${code} (${e.fr})`); continue; }
  seen.add(frN); if (arN) seen.add(arN);
  (additions[e.category] = additions[e.category] || []).push({ fr: e.fr, ar: e.ar });
}

const lists = existing.map((l) => ({
  category: l.category,
  entries: [...l.entries, ...((additions[l.category] || []))],
}));
delete additions.__done;
if (additions['Egyptian Life'] && additions['Egyptian Life'].length) {
  lists.push({ category: 'Egyptian Life', entries: additions['Egyptian Life'] });
}

let out = '// Word lists for Team Taboo (franco + Arabic). Generated by scripts/*.\n';
out += '// Every entry accepts guesses in BOTH scripts; extra spellings via accept:[]. All\n';
out += '// lists are merged into one shuffled pool (duplicates across lists auto-collapse).\n\n';
out += 'module.exports = {\n  lists: [\n';
for (const l of lists) {
  out += `    {\n      category: ${JSON.stringify(l.category)},\n      entries: [\n`;
  for (const e of l.entries) {
    let line = `        { fr: ${JSON.stringify(e.fr)}, ar: ${JSON.stringify(e.ar)}`;
    if (e.accept) line += `, accept: ${JSON.stringify(e.accept)}`;
    out += line + ' },\n';
  }
  out += '      ],\n    },\n';
}
out += '  ],\n};\n';
fs.writeFileSync(path.join(__dirname, '..', 'server', 'data', 'wordLists.js'), out, 'utf8');

const total = Object.values(additions).reduce((s, v) => s + v.length, 0);
console.log('Added per category:', JSON.stringify(Object.fromEntries(Object.entries(additions).map(([k, v]) => [k, v.length]))));
console.log('Total added:', total);
console.log('Collapsed dups:', collapsed.length ? collapsed.join(', ') : 'none');
console.log('Per category now:', lists.map((l) => `${l.category}:${l.entries.length}`).join(', '));
